using System.Buffers.Binary;
using System.Globalization;
using System.Numerics;
using System.Text;

#pragma warning disable IDE0005 // System.Text usage qualified inline below to avoid Encoding namespace clash

using DatumIngest.Model.Spatial;

namespace DatumIngest.Functions.Scalar.Spatial;

/// <summary>
/// Serializes a <see cref="DatumIngest.Model.DataKind.Mesh"/> blob to the
/// Wavefront OBJ ASCII format. Per-vertex colors emitted via the
/// <c>v X Y Z R G B</c> extension (recognized by MeshLab, CloudCompare,
/// Open3D, Blender; bare-spec OBJ readers ignore the trailing color
/// triplet). Always emits in OpenGL convention (right-handed, +Y up,
/// −Z forward) — converts from <see cref="PointCloudCoordinateFrame.CameraOpenCv"/>
/// by rotating 180° around the X axis (y→−y, z→−z) so the output renders
/// correctly in any OBJ consumer.
/// </summary>
internal static class ObjExporter
{
    /// <summary>
    /// Builds an OBJ-format UTF-8 byte buffer for the given mesh blob.
    /// </summary>
    public static byte[] Export(byte[] meshBlob, string generator)
    {
        MeshHeader header = MeshHeader.Read(meshBlob);

        int vertexCount = checked((int)header.VertexCount);
        int triangleCount = checked((int)header.TriangleCount);
        int vertexStride = header.VertexStrideBytes;
        ReadOnlySpan<byte> blobSpan = meshBlob;
        int vertexBase = MeshHeader.SizeBytes;
        int trianglesBase = vertexBase + vertexCount * vertexStride;

        int colorOffset = MeshHeader.PositionStrideBytes;
        int normalOffset = colorOffset + (header.HasColor ? MeshHeader.ColorStrideBytes : 0);
        bool flipYZ = header.CoordinateFrame == PointCloudCoordinateFrame.CameraOpenCv;
        CultureInfo inv = CultureInfo.InvariantCulture;

        StringBuilder sb = new(capacity: vertexCount * 64 + triangleCount * 32);
        sb.Append("# OBJ generated by ").Append(generator).Append('\n');
        sb.Append("o Mesh\n");

        // Vertex positions (with optional color extension).
        for (int i = 0; i < vertexCount; i++)
        {
            int slotOffset = vertexBase + i * vertexStride;
            float x = BinaryPrimitives.ReadSingleLittleEndian(blobSpan.Slice(slotOffset + 0, 4));
            float y = BinaryPrimitives.ReadSingleLittleEndian(blobSpan.Slice(slotOffset + 4, 4));
            float z = BinaryPrimitives.ReadSingleLittleEndian(blobSpan.Slice(slotOffset + 8, 4));
            if (flipYZ)
            {
                y = -y;
                z = -z;
            }

            sb.Append("v ")
                .Append(x.ToString("R", inv)).Append(' ')
                .Append(y.ToString("R", inv)).Append(' ')
                .Append(z.ToString("R", inv));

            if (header.HasColor)
            {
                float r = blobSpan[slotOffset + colorOffset + 0] / 255f;
                float g = blobSpan[slotOffset + colorOffset + 1] / 255f;
                float b = blobSpan[slotOffset + colorOffset + 2] / 255f;
                sb.Append(' ')
                    .Append(r.ToString("R", inv)).Append(' ')
                    .Append(g.ToString("R", inv)).Append(' ')
                    .Append(b.ToString("R", inv));
            }
            sb.Append('\n');
        }

        // Vertex normals (one per vertex, indexed in lockstep with positions).
        if (header.HasNormals)
        {
            for (int i = 0; i < vertexCount; i++)
            {
                int slotOffset = vertexBase + i * vertexStride;
                float nx = BinaryPrimitives.ReadSingleLittleEndian(blobSpan.Slice(slotOffset + normalOffset + 0, 4));
                float ny = BinaryPrimitives.ReadSingleLittleEndian(blobSpan.Slice(slotOffset + normalOffset + 4, 4));
                float nz = BinaryPrimitives.ReadSingleLittleEndian(blobSpan.Slice(slotOffset + normalOffset + 8, 4));
                if (flipYZ)
                {
                    ny = -ny;
                    nz = -nz;
                }
                sb.Append("vn ")
                    .Append(nx.ToString("R", inv)).Append(' ')
                    .Append(ny.ToString("R", inv)).Append(' ')
                    .Append(nz.ToString("R", inv))
                    .Append('\n');
            }
        }

        // Triangle faces. OBJ uses 1-based vertex indexing. CV→GL is a
        // proper rotation (det = +1) so winding is preserved — no need
        // to swap any pair of indices.
        for (int t = 0; t < triangleCount; t++)
        {
            uint a = BinaryPrimitives.ReadUInt32LittleEndian(blobSpan.Slice(trianglesBase + t * 12 + 0, 4));
            uint b = BinaryPrimitives.ReadUInt32LittleEndian(blobSpan.Slice(trianglesBase + t * 12 + 4, 4));
            uint c = BinaryPrimitives.ReadUInt32LittleEndian(blobSpan.Slice(trianglesBase + t * 12 + 8, 4));
            uint a1 = a + 1, b1 = b + 1, c1 = c + 1;

            if (header.HasNormals)
            {
                sb.Append("f ")
                    .Append(a1.ToString(inv)).Append("//").Append(a1.ToString(inv)).Append(' ')
                    .Append(b1.ToString(inv)).Append("//").Append(b1.ToString(inv)).Append(' ')
                    .Append(c1.ToString(inv)).Append("//").Append(c1.ToString(inv))
                    .Append('\n');
            }
            else
            {
                sb.Append("f ")
                    .Append(a1.ToString(inv)).Append(' ')
                    .Append(b1.ToString(inv)).Append(' ')
                    .Append(c1.ToString(inv))
                    .Append('\n');
            }
        }

        return System.Text.Encoding.UTF8.GetBytes(sb.ToString());
    }
}
