using System.Buffers.Binary;
using System.Globalization;

using Heliosoph.DatumV.Model.Spatial;

using AsciiEncoding = System.Text.Encoding;

namespace Heliosoph.DatumV.Functions.Scalar.Spatial;

/// <summary>
/// Serializes a <see cref="Heliosoph.DatumV.Model.DataKind.PointCloud"/> blob to
/// the binary PLY format (Polygon File Format / Stanford Triangle Format) —
/// the universal point-cloud interchange consumed by MeshLab, CloudCompare,
/// Open3D, PCL, and Blender's PLY importer. Always emits in OpenGL
/// convention (right-handed, +Y up, −Z forward); converts from
/// <see cref="PointCloudCoordinateFrame.CameraOpenCv"/> by negating Y and Z.
/// </summary>
internal static class PlyExporter
{
    /// <summary>
    /// PLY file layout: an ASCII header (newline-terminated text) followed by
    /// the binary vertex payload. We emit:
    /// <code>
    /// ply
    /// format binary_little_endian 1.0
    /// comment Generated by Heliosoph.DatumV ({generator})
    /// element vertex {N}
    /// property float x
    /// property float y
    /// property float z
    /// property uchar red       (only when HasColor)
    /// property uchar green     (only when HasColor)
    /// property uchar blue      (only when HasColor)
    /// end_header\n
    /// </code>
    /// followed by N records of <c>float×3 + uchar×3</c> (or just <c>float×3</c>
    /// for position-only clouds). The alpha channel is intentionally dropped:
    /// PLY's <c>alpha</c> property is recognized by MeshLab / CloudCompare but
    /// silently ignored by some readers, and clouds derived from RGB depth
    /// unprojection store alpha=255 uniformly anyway.
    /// </summary>
    public static byte[] Export(byte[] pointCloudBlob, string generator)
    {
        PointCloudHeader header = PointCloudHeader.Read(pointCloudBlob);

        bool sourceHasColor = header.HasColor;
        bool flipYZ = header.CoordinateFrame == PointCloudCoordinateFrame.CameraOpenCv;
        int srcStride = header.PointStrideBytes;
        int pointCount = checked((int)header.PointCount);

        // Build the ASCII header. Line endings are LF — the PLY spec mandates
        // single-character newlines, and Windows-style CRLF trips some
        // strict parsers.
        System.Text.StringBuilder textHeader = new(256);
        textHeader.Append("ply\n");
        textHeader.Append("format binary_little_endian 1.0\n");
        textHeader.Append("comment Generated by Heliosoph.DatumV (")
            .Append(generator)
            .Append(")\n");
        textHeader.Append("element vertex ")
            .Append(pointCount.ToString(CultureInfo.InvariantCulture))
            .Append('\n');
        textHeader.Append("property float x\n");
        textHeader.Append("property float y\n");
        textHeader.Append("property float z\n");
        if (sourceHasColor)
        {
            textHeader.Append("property uchar red\n");
            textHeader.Append("property uchar green\n");
            textHeader.Append("property uchar blue\n");
        }
        textHeader.Append("end_header\n");

        byte[] headerBytes = AsciiEncoding.ASCII.GetBytes(textHeader.ToString());

        int outPointStride = sizeof(float) * 3 + (sourceHasColor ? 3 : 0);
        long payloadBytes = (long)pointCount * outPointStride;
        byte[] ply = new byte[headerBytes.Length + payloadBytes];
        Span<byte> plySpan = ply;

        headerBytes.AsSpan().CopyTo(plySpan[..headerBytes.Length]);

        ReadOnlySpan<byte> srcSpan = pointCloudBlob;
        int srcBase = PointCloudHeader.SizeBytes;
        int dstOffset = headerBytes.Length;

        for (int i = 0; i < pointCount; i++)
        {
            int srcOffset = srcBase + i * srcStride;
            float x = BinaryPrimitives.ReadSingleLittleEndian(srcSpan.Slice(srcOffset + 0, 4));
            float y = BinaryPrimitives.ReadSingleLittleEndian(srcSpan.Slice(srcOffset + 4, 4));
            float z = BinaryPrimitives.ReadSingleLittleEndian(srcSpan.Slice(srcOffset + 8, 4));
            if (flipYZ)
            {
                y = -y;
                z = -z;
            }

            BinaryPrimitives.WriteSingleLittleEndian(plySpan.Slice(dstOffset + 0, 4), x);
            BinaryPrimitives.WriteSingleLittleEndian(plySpan.Slice(dstOffset + 4, 4), y);
            BinaryPrimitives.WriteSingleLittleEndian(plySpan.Slice(dstOffset + 8, 4), z);
            dstOffset += 12;

            if (sourceHasColor)
            {
                // Color bytes are stride-position +12..+15 (R, G, B, A); drop A.
                plySpan[dstOffset + 0] = srcSpan[srcOffset + 12];
                plySpan[dstOffset + 1] = srcSpan[srcOffset + 13];
                plySpan[dstOffset + 2] = srcSpan[srcOffset + 14];
                dstOffset += 3;
            }
        }

        return ply;
    }
}
